name = "NetCDF3"
uuid = "c0b278e5-4161-4a30-804d-e28c605fc747"
authors = ["Alexander Barth <barth.alexander@gmail.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
DataStructures = "0.18"
